# partly based on https://finestructure.co/blog/2016/5/16/monitoring-with-prometheus-grafana-docker-part-1

global:
  scrape_interval: 5s
  evaluation_interval: 15s 

  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']