name: CI
on: [push]
jobs:

  backend:
    name: Backend
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp
        options: --entrypoint redis-server

    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      working-directory: backend
      run: go get -v -t -d ./...

    - name: Test
      working-directory: backend
      env:
        REDIS_HOST: redis
        REDIS_PORT: ${{ job.services.redis.ports[6379] }}
      run: go test -v .

    - name: Build
      working-directory: backend
      run: go build -v .

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    steps:
    - name: Set Node.js 10.x
      uses: actions/setup-node@master
      with:
        node-version: 10.x
      id: nodejs

    - name: Check out code
      uses: actions/checkout@v1

    - name: Get dependencies
      working-directory: frontend
      run: npm install

    # - name: Lint
    #   working-directory: frontend
    #   run: npm run lint

    - name: Build
      working-directory: frontend
      run: npm run build
